/* eslint-disable */
/* oxlint-disable */
// Auto-generated by @contentrain/query — do not edit manually
// Re-generate with: npx contentrain-query generate

export type ContentStatus = 'draft' | 'published' | 'in_review' | 'rejected' | 'archived'

export interface AuditEvent {
  id: string
  actor: string
  severity?: 'info' | 'warning' | 'critical'
  summary?: string
  target: string
  timestamp: string
  title: string
}

export interface BillingPlan {
  id: string
  cadence?: string
  cta_href?: string
  cta_label?: string
  featured?: boolean
  features?: string[]
  name: string
  price_label: string
  status_badge?: string
}

export interface DashboardOverview {
  environment_badge?: string
  eyebrow?: string
  primary_cta_href?: string
  primary_cta_label?: string
  status_note?: string
  summary: string
  title: string
}

export interface Footer {
  blurb?: string
  columns?: { links?: { href: string; label: string }[]; title: string }[]
  legal_notice?: string
}

export interface Navigation {
  announcement_label?: string
  cta_href?: string
  cta_label?: string
  items?: { emphasis?: boolean; href: string; label: string }[]
}

export interface OpsNotice {
  id: string
  body: string
  cta_href?: string
  cta_label?: string
  title: string
  tone?: 'info' | 'warning' | 'success'
}

export interface SeoDefaults {
  canonical_base: string
  meta_description: string
  meta_title: string
  og_image?: string
}

export interface SettingsGroup {
  id: string
  items?: { hint?: string; label: string; status?: string; value: string }[]
  summary?: string
  title: string
}

export interface SiteSettings {
  default_locale: string
  og_image?: string
  site_name: string
  site_tagline?: string
  theme_name: string
}

export interface TenantProfile {
  id: string
  accent_label?: string
  available_locales?: string[]
  docs_href?: string
  industry?: string
  logo_mark?: string
  name: string
  slug: string
  summary: string
  support_email?: string
  terminology?: { label: string; value: string }[]
  theme_badge?: string
}

export type UiCopy = Record<string, string>

export interface QueryBuilder<T> {
  locale(lang: string): QueryBuilder<T>
  where<K extends keyof T>(field: K, value: T[K]): QueryBuilder<T>
  sort<K extends keyof T>(field: K, order?: 'asc' | 'desc'): QueryBuilder<T>
  limit(n: number): QueryBuilder<T>
  offset(n: number): QueryBuilder<T>
  include(...fields: string[]): QueryBuilder<T>
  first(): T | undefined
  all(): T[]
}

export interface SingletonAccessor<T> {
  locale(lang: string): SingletonAccessor<T>
  include(...fields: string[]): SingletonAccessor<T>
  get(): T
}

export interface DictionaryAccessor {
  locale(lang: string): DictionaryAccessor
  get(): Record<string, string>
  get(key: string): string | undefined
  get(key: string, params: Record<string, string | number>): string
}

export interface DocumentQuery<T> {
  locale(lang: string): DocumentQuery<T>
  where<K extends keyof T>(field: K, value: T[K]): DocumentQuery<T>
  include(...fields: string[]): DocumentQuery<T>
  bySlug(slug: string): T | undefined
  first(): T | undefined
  all(): T[]
}

export declare function query(model: 'audit-event'): QueryBuilder<AuditEvent>
export declare function query(model: 'billing-plan'): QueryBuilder<BillingPlan>
export declare function query(model: 'ops-notice'): QueryBuilder<OpsNotice>
export declare function query(model: 'settings-group'): QueryBuilder<SettingsGroup>
export declare function query(model: 'tenant-profile'): QueryBuilder<TenantProfile>
export declare function query(model: string): QueryBuilder<Record<string, unknown>>

export declare function singleton(model: 'dashboard-overview'): SingletonAccessor<DashboardOverview>
export declare function singleton(model: 'footer'): SingletonAccessor<Footer>
export declare function singleton(model: 'navigation'): SingletonAccessor<Navigation>
export declare function singleton(model: 'seo-defaults'): SingletonAccessor<SeoDefaults>
export declare function singleton(model: 'site-settings'): SingletonAccessor<SiteSettings>
export declare function singleton(model: string): SingletonAccessor<Record<string, unknown>>

export declare function dictionary(model: 'ui-copy'): DictionaryAccessor
export declare function dictionary(model: string): DictionaryAccessor

export declare function document(model: string): DocumentQuery<Record<string, unknown>>

export interface ContentrainClient {
  query(model: 'audit-event'): QueryBuilder<AuditEvent>
  query(model: 'billing-plan'): QueryBuilder<BillingPlan>
  query(model: 'ops-notice'): QueryBuilder<OpsNotice>
  query(model: 'settings-group'): QueryBuilder<SettingsGroup>
  query(model: 'tenant-profile'): QueryBuilder<TenantProfile>
  query(model: string): QueryBuilder<Record<string, unknown>>
  singleton(model: 'dashboard-overview'): SingletonAccessor<DashboardOverview>
  singleton(model: 'footer'): SingletonAccessor<Footer>
  singleton(model: 'navigation'): SingletonAccessor<Navigation>
  singleton(model: 'seo-defaults'): SingletonAccessor<SeoDefaults>
  singleton(model: 'site-settings'): SingletonAccessor<SiteSettings>
  singleton(model: string): SingletonAccessor<Record<string, unknown>>
  dictionary(model: 'ui-copy'): DictionaryAccessor
  dictionary(model: string): DictionaryAccessor
  document(model: string): DocumentQuery<Record<string, unknown>>
}

export declare function createContentrainClient(): ContentrainClient

